file=open("demo.txt","w")
file.write("hello everyone, how are you all?\n")
file.write("Today we are going to study python language")
file.close()

file=open("demo.txt","r")
a=file.read()
file.seek(0)
b=file.readlines()
file.seek(0)
c=file.readline()
print(a)
print(b)
print(c)
file.close()